#!/usr/bin/env python3
"""Generate android/src/language_textures.h: the file select's save-slot
labels ("Quest Log 1-3" on the USA disc) in German, French, Spanish and
Italian, for the in-app language overlay (android/src/language_overlay.c).

They are drawn here, not taken from a disc: white Open Sans Condensed
ExtraBold (Apache-2.0) with a black outline, as the USA texture is styled,
encoded as the USA texture's format (IA4, 176x48, GameCube 8x4 tiles) and
stored zlib-compressed. Rerun after changing a word:

    python3 scripts/android/language_textures.py [--font OpenSans-CondensedExtraBold.ttf]
"""
import argparse
import zlib
from pathlib import Path

from PIL import Image, ImageDraw, ImageFilter, ImageFont

ROOT = Path(__file__).resolve().parents[2]
W, H = 176, 48
# The word each language's own text uses for a save slot (the PAL messages:
# "Spielstand wählen", "Choisir un fichier.", "Selección de archivo",
# "Seleziona i dati.").
SLOT = ["Spielstand", "Fichier", "Archivo", "Dati"]


def render_ia4(font_path: str, text: str) -> bytes:
    """The outline is the fill grown by a max filter: FreeType's stroker
    leaves holes where this font's contours overlap."""
    scale = 4
    w, h = W * scale, H * scale
    pad = 3 * scale                      # the outline, as wide as the USA one
    size = 30 * scale                    # the USA cap height at most
    while True:
        font = ImageFont.truetype(font_path, size)
        box = ImageDraw.Draw(Image.new("L", (1, 1))).textbbox((0, 0), text, font=font)
        if box[2] - box[0] + 2 * pad <= w - 4 * scale and box[3] - box[1] + 2 * pad <= h - 2 * scale:
            break
        size -= scale
    x = (w - (box[2] - box[0])) // 2 - box[0]
    y = (h - (box[3] - box[1])) // 2 - box[1]
    fill = Image.new("L", (w, h), 0)
    ImageDraw.Draw(fill).text((x, y), text, font=font, fill=255)
    alpha = fill.filter(ImageFilter.MaxFilter(2 * pad + 1)).resize((W, H), Image.LANCZOS)
    fill = fill.resize((W, H), Image.LANCZOS)
    a, l = alpha.load(), fill.load()
    data = bytearray()
    for ty in range(0, H, 4):
        for tx in range(0, W, 8):
            for yy in range(4):
                for xx in range(8):
                    data.append(((a[tx + xx, ty + yy] * 15 + 127) // 255) << 4
                                | ((l[tx + xx, ty + yy] * 15 + 127) // 255))
    return bytes(data)


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--font", default="/usr/share/fonts/opensans/OpenSans-CondensedExtraBold.ttf")
    ap.add_argument("--out", type=Path, default=ROOT / "android/src/language_textures.h")
    a = ap.parse_args()
    raw = b"".join(render_ia4(a.font, f"{word} {n}") for word in SLOT for n in (1, 2, 3))
    packed = zlib.compress(raw, 9)
    lines = ["// Generated by scripts/android/language_textures.py -- do not edit.",
             "// The file select's save-slot labels, [language de/fr/es/it][slot 1-3],",
             f"// IA4 {W}x{H} each, zlib-compressed.",
             "#pragma once",
             f"#define BW_LANG_SLOT_TEX_W {W}",
             f"#define BW_LANG_SLOT_TEX_H {H}",
             f"#define BW_LANG_SLOT_TEX_RAW {len(raw)}u",
             "static const unsigned char kBwLangSlotTextures[] = {"]
    for i in range(0, len(packed), 20):
        lines.append("    " + ", ".join(f"0x{b:02X}" for b in packed[i:i + 20]) + ",")
    lines.append("};")
    a.out.write_text("\n".join(lines) + "\n")
    print(f"{a.out}: {len(raw)} bytes, {len(packed)} compressed")


if __name__ == "__main__":
    main()
